# 9 March 2020
# WD: /home/jkimball/haasx092/circos/200309_version
# Purpose of this code is to make an updated circos plot with annotation details generated by Marissa and Tom

# Load required packages
library(circlize)

# Draw Ideogram
# ** Note: format for this karyotype file differs slightly from calling on the command line. File must contain 5 columns. First column is just a number in sequential order, the second column is start position, the third column is the end position, the fourth column is the chromosome/scaffold name, and the fifth column is color. **
circos.initializeWithIdeogram(cytoband="200309_karyotype.zizania.txt")

# Long Terminal Repeats
LTRs <- read.table("LTRs.bed")

col_fun = colorRamp2(c(-1,0,1), c("green", "black", "red"))

# Add heatmap for LTRs
circos.genomicHeatmap(bed = LTRs, col = col_fun, side = "inside", border="white")