# 12 May 2020
# WD: /home/jkimball/haasx092/circos/200511_version
# Purpose of this script is to extract genomic features from bed files generated by Marissa and Tom
# This particular script is for long terminal repeats (LTRs)

# Load required packages
library(data.table)

# Load data and give meaningful names
LTRs <- fread("LTRs.bed")
setnames(LTRs, c("scaffold", "start", "end", "type"))

Gypsy <- LTRs[type == "LTR/Gypsy"]
Copia <- LTRs[type == "LTR/Copia"]
Other_LTR <- LTRs[type != "LTR/Gypsy" & type != "LTR/Copia"]

# Define scaffolds of interest
scaffolds <- c("Scaffold_1", "Scaffold_3", "Scaffold_7", "Scaffold_9", "Scaffold_13", "Scaffold_18", "Scaffold_48", "Scaffold_51", "Scaffold_70",
				"Scaffold_93", "Scaffold_415", "Scaffold_693", "Scaffold_1062", "Scaffold_1063", "Scaffold_1064", "Scaffold_1065")

# Gypsy
for (i in scaffolds){
Gypsy[scaffold==i, .N, key=.(scaffold, bin=start%/%1000000)] -> gypsy_output
gypsy_output[, start := as.integer(bin*1e6)] # add a column for the start of each bin
gypsy_output[, end := as.integer(start+1e6)] # add a colum for the end of each bin
setcolorder(gypsy_output, c("scaffold", "start", "end", "N", "bin")) # change column order
gypsy_output[, bin := NULL] # remove unnnecessary column
gypsy_output[, scaffold := sub("Scaffold_", "zp", scaffold)]
myfile <- paste0(i, "_Gypsy_binned.txt")
write.table(gypsy_output, file = myfile, row.names = FALSE, col.names = FALSE, quote = FALSE)
}

# Copia
for (i in scaffolds){
Copia[scaffold==i, .N, key=.(scaffold, bin=start%/%1000000)] -> copia_output
copia_output[, start := as.integer(bin*1e6)] # add a column for the start of each bin
copia_output[, end := as.integer(start+1e6)] # add a colum for the end of each bin
setcolorder(copia_output, c("scaffold", "start", "end", "N", "bin")) # change column order
copia_output[, bin := NULL] # remove unnnecessary column
copia_output[, scaffold := sub("Scaffold_", "zp", scaffold)]
myfile <- paste0(i, "_Copia_binned.txt")
write.table(copia_output, file = myfile, row.names = FALSE, col.names = FALSE, quote = FALSE)
}

# Other LTRs
for (i in scaffolds){
Other_LTR[scaffold==i, .N, key=.(scaffold, bin=start%/%1000000)] -> other_output
other_output[, start := as.integer(bin*1e6)] # add a column for the start of each bin
other_output[, end := as.integer(start+1e6)] # add a colum for the end of each bin
setcolorder(other_output, c("scaffold", "start", "end", "N", "bin")) # change column order
other_output[, bin := NULL] # remove unnnecessary column
other_output[, scaffold := sub("Scaffold_", "zp", scaffold)]
myfile <- paste0(i, "_otherLTR_binned.txt")
write.table(other_output, file = myfile, row.names = FALSE, col.names = FALSE, quote = FALSE)
}