# 10 March 2020
# WD: /home/jkimball/haasx092/circos/200309_version
# Purpose of this script is to extract genomic features from bed files generated by Marissa and Tom
# This particular script is for DNA elements

# Load required packages
library(data.table)

# Load data and give meaningful names
DNA <- fread("DNA.bed")
setnames(DNA, c("scaffold", "start", "end", "type"))

# Define scaffolds of interest
scaffolds <- c("Scaffold_1", "Scaffold_3", "Scaffold_7", "Scaffold_9", "Scaffold_13", "Scaffold_18", "Scaffold_48", "Scaffold_51", "Scaffold_70",
				"Scaffold_93", "Scaffold_415", "Scaffold_693", "Scaffold_1062", "Scaffold_1063", "Scaffold_1064", "Scaffold_1065")

for (i in scaffolds){
DNA[scaffold==i, .N, key=.(scaffold, bin=start%/%1000000)] -> output
output[, start := as.integer(bin*1e6)] # add a column for the start of each bin
output[, end := as.integer(start+1e6)] # add a colum for the end of each bin
setcolorder(output, c("scaffold", "start", "end", "N", "bin")) # change column order
output[, bin := NULL] # remove unnnecessary column
output[, scaffold := sub("Scaffold_", "zp", scaffold)]
myfile <- paste0(i, "_DNA_binned.txt")
write.table(output, file = myfile, row.names = FALSE, col.names = FALSE, quote = FALSE)
}

## After writing to files, I manually edited the name of each scaffold in these files with vim. The command is: %s/zp3/zp2/g to search for "zp3" and replace it with "zp2"
## This is to match the chromosome designations in the circos configuration file. Changing the configuration file names to match the numbering system to match the scaffold numbers did not work.
## To do the search, you  must open the file in vim, hit "esc" and then "shift" + ":"
## You will then be able to type the search command on the prompt at the bottom of the screen.
# The next lines explain which scaffold (left side) corresponse to which ordered scaffold (right side)
## zp1 = zp1
## zp3 = zp2
## zp7 = zp3
## zp9 = zp4
## zp13 = zp5
## zp18 = zp6
## zp48 = zp7
## zp51 = zp8
## zp70 = zp9
## zp93 = zp10
## zp415 = zp11
## zp693 = zp12
## zp1062 = zp13
## zp1063 = zp14
## zp1064 = zp15
## zp1065 = zp16